version: '3.9'

volumes:
  postgres_data:

services:
  app:
    build:
      context: .
      dockerfile: configs/docker/app/Dockerfile
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    restart: always
    env_file:
      - .env
    networks:
      - django_network
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:14.9-alpine3.18
    restart: always
    env_file:
      - .env
    networks:
      - django_network
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  django_network:
